### ISSUE TITLE
New install - Tradesafe plugin is broken

### ISSUE THREAD

**Issue by lifeboy** [tradesafe/plugin-woocommerce#32]
New WP install: 6.0.2.  Install this plugin and it get the message "There has been a critical error on this website" when activating the plugin.

Ubuntu 22.04
PHP 8.1
Apache/2.4.52

The /var/log/apache2/wynklub/.com/error.log has this:

```
[Tue Sep 13 22:31:12.750248 2022] [php:error] [pid 164] [client 192.168.131.150:47008] PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class "TradeSafe" not found in /var/www/wordpress/wp-includes/class-wp-hook.php:307\nStack trace:\n#0 /var/www/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()\n#1 /var/www/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action()\n#2 /var/www/wordpress/wp-settings.php(598): do_action()\n#3 /var/www/wordpress/wp-config.php(95): require_once('...')\n#4 /var/www/wordpress/wp-load.php(50): require_once('...')\n#5 /var/www/wordpress/wp-admin/admin.php(34): require_once('...')\n#6 /var/www/wordpress/wp-admin/plugins.php(10): require_once('...')\n#7 {main}\n  thrown in /var/www/wordpress/wp-includes/class-wp-hook.php on line 307, referer: http://wynklub.com/wp-admin/plugin-install.php?s=tradesafe&tab=search&type=term


```

**Comment by tradesafe-ops** [comment]
Could you please confirm that the following files are present in the plugin and not zero bytes in size. This type of error only happens if there are files missing or they are empty.

Dir: /tradesafe-payment-gateway/src/

class-tradesafe.php
class-tradesafedokan.php
class-tradesafeprofile.php
class-wc-gateway-tradesafe.php

**Comment by lifeboy** [comment]
```
wynklub:/var/www/wordpress/wp-content/plugins/tradesafe-payment-gateway/src# ls -la
total 104
drwxr-xr-x 2 www-data www-data  4096 Sep 13 22:31 .
drwxr-xr-x 8 www-data www-data  4096 Sep 13 22:31 ..
-rw-r--r-- 1 www-data www-data 25197 Sep 13 22:31 class-tradesafedokan.php
-rw-r--r-- 1 www-data www-data 16210 Sep 13 22:31 class-tradesafe.php
-rw-r--r-- 1 www-data www-data 19812 Sep 13 22:31 class-tradesafeprofile.php
-rw-r--r-- 1 www-data www-data 29273 Sep 13 22:31 class-wc-gateway-tradesafe.php
```

**Comment by tradesafe-ops** [comment]
Everything looks okay there. could you please try deleting and re-uploading the plugin.

**Comment by lifeboy** [comment]
Nope. I have done a fresh WP install 2 times, deactivated all other plugins, but as soon as I activate the tradesafe plugin the error occurs.

I have now created a snapshot at the point just before the installation.  Also enabled debug in WP.  Here is the result:

> Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class "TradeSafe" not found in /var/www/wordpress/wp-includes/class-wp-hook.php:307 Stack trace: #0 /var/www/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters() #1 /var/www/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action() #2 /var/www/wordpress/wp-settings.php(598): do_action() #3 /var/www/wordpress/wp-config.php(95): require_once('...') #4 /var/www/wordpress/wp-load.php(50): require_once('...') #5 /var/www/wordpress/wp-admin/admin.php(34): require_once('...') #6 /var/www/wordpress/wp-admin/plugins.php(10): require_once('...') #7 {main} thrown in /var/www/wordpress/wp-includes/class-wp-hook.php on line 307
> There has been a critical error on this website. Please check your site admin email inbox for instructions.
> 
> [Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)
> 

The apache access log is below:

https://pastebin.com/uxUAipgK

**Comment by tradesafe-ops** [comment]
We have pushed an update to the plugin. Could you please install version 2.5.2 this should resolve the issue.

**Comment by lifeboy** [comment]
It works now!  Great! Thank you!
